version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - ./player/audiobooks:/audiobooks
      - ./player/podcasts:/podcasts
      - ./player/config:/config
      - ./player/metadata:/metadata
  ytdl_material:
    environment:
      ALLOW_CONFIG_MUTATIONS: 'true'
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
    restart: always
    depends_on:
      - ytdl-mongo-db
    volumes:
      - ./downloader/appdata:/app/appdata
      - ./player/audiobooks/top100:/app/audio
      - ./downloader/video:/app/video
      - ./downloader/subscriptions:/app/subscriptions
      - ./downloader/users:/app/users
    ports:
      - "8998:17442"
    image: tzahi12345/youtubedl-material:latest
  ytdl-mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    container_name: mongo-db
    restart: always
    volumes:
      - ./downloader/db/:/data/db
